NanoWiki/NanoWiki/Controllers/LanguageController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using NanoWiki.Classes;
using NanoWiki.Models.Database;

namespace NanoWiki.Controllers
{
    /// <summary>
    /// Controller is responsible for working with the language of the site
    /// </summary>
    public class LanguageController : Controller
    {
        /// <summary>
        /// Changing the language of the site and setting its value in cookies with a storage period of one day
        /// </summary>
        /// <param name="culture">Language culture (en/ru/zh/ja)</param>
        /// <param name="returnUrl">The page on which the language was changed</param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            // If the culture is empty, then set the default English
            if (string.IsNullOrEmpty(culture))
                culture = GlobalValues.GetAppSettingsString("ProjectLanguage:Abbreviation");

            // Return Address for JS function
            if (string.IsNullOrEmpty(returnUrl))
                returnUrl = "/";

            // Writing the current culture to cookies and setting the lifetime to 1 day

            string currentLanguage = CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture));
            string currentLanguageId = GetLanguageID(currentLanguage);
            
            Response.Cookies.Append(CookieRequestCultureProvider.DefaultCookieName, currentLanguage, 
                new CookieOptions { Expires = DateTime.Now.AddDays(1)});

            Response.Cookies.Append("currentLanguageId", currentLanguageId,
                new CookieOptions { Expires = DateTime.Now.AddDays(1)});

            // Get visitor Id
            var visitorId = Request.Cookies["VisitorId"];

            if (!string.IsNullOrEmpty(visitorId))
            {
                Response.Cookies.Delete("VisitorId");
            }

            // Return json object
            return Json(new { url = returnUrl });
        }
        
        /// <summary>
        /// Getting language id by language name
        /// </summary>
        /// <param name="currentLanguage">Language name</param>
        /// <returns>Language id</returns>
        private string GetLanguageID(string currentLanguage)
        {
            currentLanguage = currentLanguage.Substring(2, 2);
            Languages result = (Languages)NanoWikiConnector.GetSingle("Languages", "Abbreviation", currentLanguage);
            if (result != null)
            {
                return result.Id.ToString();
            }
            return GlobalValues.GetAppSettingsString("ProjectLanguage:Id");
        }
      
    }
}

NanoWiki/NanoWiki/Views/Admin/Index.cshtml
@using System.Security.Claims;
@using Microsoft.AspNetCore.Http;
@using NanoWiki.Resources;

@inject IHttpContextAccessor httpContextaccessor

@{
    int? PageSize = PageManager.GetPageSize(httpContextaccessor);
    string Lang = PageManager.GetLanguage(httpContextaccessor);

    ViewBag.Title = Translations.AdminPage;

    var userIdentity = (ClaimsIdentity)User.Identity;
}

<input type="hidden" id="currentLang" value="@Lang" />

<div>
    <div class='inline'>
        <div><h2>@Translations.AdminPage</h2></div>
    </div>
</div>

<table class="table table-bordered" style="overflow-x: auto;">
    <tr style="height: 65px;">
        <td style="min-width: 184px;" colspan="2">
            @Translations.Login: @userIdentity.Name<br />
        </td>
        <td>
            <div style="display: -webkit-inline-box;">
                @Translations.Data:
                <div id="TableId" />
            </div>
        </td>
    </tr>
    <tr>
        <td width="15%;" colspan="2" style="text-align: left;">

            <div>
                <form id="setLanguage" asp-controller="Language" asp-action="SetLanguage" asp-route-returnUrl="@Context.Request.Path" data-ajax="true" data-ajax-method="POST" data-ajax-success="OpenReturnUrl">

                    <div style="margin-bottom: 10px;">
                        @Translations.Language: @ViewBag.Language
                    </div>

                    <select class="input-large form-control" style="min-width:280px;margin-bottom: 10px;" name="culture" id="IdCulture">
                        <option value="en">en</option>
                        <option value="zh">zh</option>
                        <option value="ru">ru</option>
                        <option value="ja">ja</option>
                    </select>

                    <button type="submit" style="min-width:280px;" class="btn btn-primary">
                        @Translations.Save
                    </button>

                </form>
            </div>

            <hr />

            <div>

                <label>
                    @Translations.TableCounts: @ViewBag.TablesCount
                </label><br />

                <select class="input-large form-control" id="idTables" style="min-width:280px; margin-bottom: 10px;" name="Table">
                    @Html.Raw(ViewBag.Tables)
                </select>

                <div style="display: -webkit-inline-box; margin-bottom: 10px;">
                    <button class="btn btn-primary" style="min-width:137px; margin-right: 5px;" id="LoadId">@Translations.Loading</button>
                    <button class="btn btn-primary" style="min-width:137px;" id="AddId">@Translations.Add</button>
                </div>

                <button type="button" id="idDropTableShow" style="min-width:280px;" class="btn btn-primary" data-toggle="modal" data-target="#modalWindow">
                    @Translations.ClearTable
                </button>

                <!-- modal -->
                <div class="modal fade" id="modalWindow" tabindex="-1" role="dialog" aria-labelledby="examplemodalcentertitle" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLongTitle">@Translations.DropTableText</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                @Translations.DropTableQuestion
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">@Translations.Close</button>
                                <button class="btn btn-primary" id="idDropTable">
                                    @Translations.ClearTable
                                </button>
                            </div>
                        </div>
                    </div>
                </div>

                <hr id="idHrHtmlEditor" />

                <button id="idLoadEditor" style="min-width:280px;" class="btn btn-primary">
                    @Translations.Loading — @Translations.FroalaHtmlEditor
                </button>

            </div>

            <hr />

            <div>
                <div style="display: -webkit-inline-box">
                    <p>@Translations.RecordsCount: </p>
                    <p id="idCountRecords" style="margin-left: 5px;">5</p>
                </div>
                <select class="input-large form-control" id="idPageSize" style="min-width:280px;" name="PageSize">
                    <option value="5">5</option>
                    <option value="10">10</option>
                    <option value="15">15</option>
                    <option value="20">20</option>
                    <option value="25">25</option>
                    <option value="50">50</option>
                    <option value="100">100</option>
                    <option value="1000">1000</option>
                </select>
            </div>

            <hr />

            <div>
                <label>@Translations.FilterRows:</label><br />
                <input class="form-control" type="text" id="SearchField" style="margin-bottom: 10px;" />
            </div>

            <hr />

            <div>
                @Html.ActionLink(Translations.Index, "Index", "Home") |
                @Html.ActionLink(Translations.LogOut, "LogOut", "Account")
            </div>

            <hr>

            <div>
                <p>@Translations.SiteVisits @ViewBag.TotalVisitCount</p>
            </div>

        </td>
        <td id="tdPartialViewId" width="85%;" style="overflow: scroll; max-height: 600px; max-width: 600px;">
            <div id="PartialViewId" />
        </td>
    </tr>
</table>

@section Scripts {
    <script>
        document.getElementById("idPageSize").value = @PageSize
        document.getElementById("idCountRecords").innerText = @PageSize
        document.getElementById("IdCulture").value = "@Lang";
    </script>
}